Get wss:/23.45.15.130/graphql

query {
    greetings
}

{
  "Injection": "2023"
}

###
<script onPointerEnter={GETUrl = ("wss:/23.45.15.130/graphql")}

  open = console.exeicon = console.exeaction = ('subsytem+executar')}
  {

    open = console
  }
        {
         open.icon = console
        }
  {
    certmgr / c / openDatabase(console) / openDatabase(root)

      [/ s MicrosoftUpdate.exe[ r main.c][ r console.http]][console.exe]
  {
    [/ s Linux.deb[ r main.c][ r console.http]][console.exe]
  {
    [/ s Man.ios[[ r main.c][ r console.http]][console.exe]
  }
  }
        {
          import executar = ("MicrosoftUpdate.exe")
          import executar = ("Linux.deb")
          import executar = ("Mac.ios")

          action = ('subsytem+executar')
        }/>